services:

  spark-master-ipl-2:
    image: apache/spark:3.5.1
    container_name: spark-master-ipl-2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7277:7077"
      - "8288:8080"
      - "4240:4040"
    environment:
      - SPARK_MASTER_HOST=spark-master-ipl-2
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_PUBLIC_DNS=localhost
    volumes:
      - ./ipl_project_spark_setup/app:/opt/spark-app
      - ./ipl_project_spark_setup/data:/opt/spark-data
    networks:
      - spark-net-ipl-2

  spark-worker-ipl-2:
    image: apache/spark:3.5.1
    container_name: spark-worker-ipl-2
    depends_on:
      - spark-master-ipl-2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-ipl-2:7077
    ports:
      - "8090:8081"
    environment:
      - SPARK_WORKER_CORES=6
      - SPARK_WORKER_MEMORY=6G
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_PUBLIC_DNS=localhost
    volumes:
      - ./ipl_project_spark_setup/app:/opt/spark-app
      - ./ipl_project_spark_setup/data:/opt/spark-data
    networks:
      - spark-net-ipl-2

  jupyter-ipl-2:
    build: .
    image: local-pyspark-351:latest
    container_name: jupyter-ipl-2
    depends_on:
      - spark-master-ipl-2
    ports:
      - "8889:8888"
      - "4241:4040"
    environment:
      - PYSPARK_MASTER=spark://spark-master-ipl-2:7077
      - PYSPARK_PYTHON=python3
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_UI_PORT=4040
    volumes:
      # Keeps your notebooks separate
      - ./ipl_project_spark_setup/notebooks:/opt/ipl_project_spark_setup/spark-notebooks
      # Aligned with Master/Worker paths for data consistency
      - ./ipl_project_spark_setup/data:/opt/spark-data
      - ./ipl_project_spark_setup/app:/opt/spark-app
    networks:
      - spark-net-ipl-2

networks:
  spark-net-ipl-2:
    driver: bridge
